version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"    # LocalStack gateway
      - "4571:4571"
    environment:
      - SERVICES=lambda,apigateway,iam
      - DEBUG=1
      - LAMBDA_DOCKER_NETWORK=aws-localsetup_default
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    name: aws-localsetup_default 